### ISSUE TITLE
JQuery Basics Review

### ISSUE THREAD

**Issue by siobhanmcgill** [audra-todd/jQuery-Apps#1]
Hey Audra,

I'm checking out your JQuery Basics repository, and it looks great except for one problem. The mobile menu HTML files (the index.html file at least) have all the HTML duplicated. If you can fix that, you'll get my thumbs up.

**Comment by audra-todd** [comment]
Ohhhh darn.  Thanks!  Since each project had the original completed files designated to download, I would go in and start fresh underneath the old script (following allow with the videos) and erase the original.  Obviously didn't follow through on that one.

Thanks for letting me know!
~Audra

**Comment by audra-todd** [comment]
Done & done, thanks!
